# Generated by Django 4.1.4 on 2023-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_saved_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latest_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='link',
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='review',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='website',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
